module.exports = [
    // List of ideas, the second item in the nested array for reference link.
    // Leave as "" if no link is applicable.
    ["Check for out of date dependencies that are upgrade safe", ""],
    ["Scan your code base for hashes or other security tokens", ""],
    ["Supply adequate test coverage", ""],
    ["Document your architecture (if you haven’t)", ""],
    ["Break up components so they can be replaced in relative isolation, start with the biggest", ""],
    ["Add descriptive top-of-file comments", ""],
    ["Suffix variables and function with units where appropriate (ie - `duration_min`)", ""],
    ["Revoke access or uninstall unused GitHub applications", ""],
    ["Update array and object constructors to literals", ""],
    ["Clear vendor seats occupied by individuals who are not longer contributors", ""],
    ["Scan low-churn files for `TODOs` and `FIXMEs`", ""],
    ["Update your Bitbucket Server instance to the latest release", ""],
    ["Write, or update, your style guide", ""],
    ["Ensure `Math.random()` isn't used for generating secure tokens", ""],
    ["Scan for `console.log()` or `print` instances left over from debugging", ""],
    ["Remove any commented code - or add a message explaining why it's there", ""],
    ["Scan for `console.log()` or `print` instances left over from debugging", ""],
    ["Look for important credentials and/or secret keys accidentally placed in shared repositories", ""],
    ["Make sure any pages responsible for sensitive data transfer aren't served over HTTP", ""],
    ["Remove duplicate ids from any passworded or payment forms", ""],
    ["Use a copy/paste detector (like PMD) to reduce code duplication", ""],
    ["Remove duplicate ids from any passworded or payment forms", ""],
    ["Sort long lists of imports in alphabetical order", ""],
    ["Make sure all `switch` statements have a default return", ""],
    ["Separate stateful aspects from rendering", ""],
    ["Handle errors with early returns", ""],
    ["Separate stateful aspects from rendering", ""],
    ["Name and describe packages before they're used", ""],
    ["Disable unnecessary and trivial warnings in `.eslintrc`", ""],
    ["Calibrate linter rules to the most widely accepted set of standards", ""],
    ["Write unit tests for anticipated edge cases", ""],
    ["Add unit tests based on edge case bugs observed in production", ""],
    ["Write unit tests for anticipated edge cases", ""]
]
